amf:
  #addr: 192.168.123.252 #127.0.0.5                 # The address or hostname of the AMF.
  #bind_addr: 192.168.123.250 # 127.0.0.1              # A local IP that the gNB binds to for traffic from the AMF.
  addr: 172.27.2.41                 # The address or hostname of the AMF.
  #addr: 172.27.2.43                 # The address or hostname of the AMF.
  #addr: 10.1.7.24                 # The address or hostname of the AMF.
  bind_addr: 172.27.2.231              # A local IP that the gNB binds to for traffic from the AMF.
  #sctp_rto_max: 5000
  #sctp_init_max_attempts: 10
  #sctp_max_init_timeo: 8000

ru_sdr:
  device_driver: uhd                # The RF driver name.
  device_args: type=x300,addr=192.168.40.2,clock=internal,sampling_rate=46.08e6,master_clock_rate=184.32e6,send_frame_size=8000,recv_frame_size=8000            # Optionally pass arguments to the selected RF driver.
  #device_args: type=x300,clock=internal,sampling_rate=46.08e6,clock_source=internal,time_source=internal,master_clock_rate=184.32e6            # Optionally pass arguments to the selected RF driver.
  #device_args: type=x300,clock=internal,sampling_rate=30.72e6            # Optionally pass arguments to the selected RF driver.
   #device_args: type=x300,clock=internal,sampling_rate=11.52e6       # Optionally pass arguments to the selected RF driver.
  clock:                       # Specify the clock source used by the RF.
  sync:                        # Specify the sync source used by the RF.
  srate: 46.08                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 30                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 30 # 37.5                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 628334                  # ARFCN of the downlink carrier (center frequency).
  band: 78                          # The NR band.
  channel_bandwidth_MHz: 40         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 1                            # Tracking area code (needs to match the core configuration).
  #tac: 81 #1                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
  #pci: 16 # 1                            # Physical cell ID.
      
log:
  filename: /home/fiveg/srsran_5gnb_demo.log            # Path of the log file.
  all_level: debug                # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
